apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
      - name: frontend
        image: your-frontend-image:dev
        ports:
        - containerPort: 80
