apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-prod
  template:
    metadata:
      labels:
        app: mysql-prod
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Senha123"
        - name: MYSQL_DATABASE
          value: "meubanco"
        ports:
        - containerPort: 3306
